-- KLOVR Precision — the whole database, in order.
--
-- Generated by scripts/build-schema.js from supabase/migrations/. Do not edit
-- this file; edit the migration and regenerate, or CI will notice.
--
-- Paste the lot into the Supabase SQL editor and run it once, on a new project.
--
-- It is wrapped in a transaction, so if anything fails nothing is applied and
-- you can fix it and paste again. That also means running it a second time on a
-- database that already has these tables stops at the first CREATE TYPE and
-- rolls the whole thing back, rather than half-applying anything. To change
-- something later, write a new migration rather than re-running this.
--
-- 10 migrations, in this order:
--    1. 0001_schema.sql
--    2. 0002_rls.sql
--    3. 0003_seed.sql
--    4. 0004_create_order.sql
--    5. 0005_storefront_fields.sql
--    6. 0006_catalogue_content.sql
--    7. 0007_ffl_directory.sql
--    8. 0008_site_events.sql
--    9. 0009_order_notices.sql
--   10. 0010_product_editor.sql

begin;

-- ==========================================================================
-- 0001_schema.sql
-- ==========================================================================

-- KLOVR Precision — staff/admin schema
-- Money is stored in integer cents. Never floats.

create extension if not exists "pgcrypto";

-- ---------------------------------------------------------------- enums
create type delivery_rule as enum ('door','ffl','nfa');
create type order_status  as enum ('new','paid','hold','at_dealer','shipped','complete','cancelled');
create type destination   as enum ('door','ffl');

-- ---------------------------------------------------------------- staff
-- One row per employee, keyed to the Supabase auth user. Membership of this
-- table is what "is an employee" means; there is no self-signup.
create table public.staff (
  id          uuid primary key references auth.users on delete cascade,
  email       text not null,
  full_name   text,
  role        text not null default 'staff' check (role in ('staff','manager','owner')),
  created_at  timestamptz not null default now()
);

-- ---------------------------------------------------------------- catalogue
create table public.products (
  id              uuid primary key default gen_random_uuid(),
  sku             text unique not null,
  name            text not null,
  category        text,
  description     text[]  not null default '{}',
  specs           jsonb   not null default '[]',
  images          text[]  not null default '{}',
  price_cents     integer not null check (price_cents >= 0),
  stock           integer not null default 0 check (stock >= 0),
  built_to_order  boolean not null default false,
  -- how this item is allowed to reach a buyer. Drives checkout, not just labels.
  delivery        delivery_rule not null default 'door',
  -- states we may not send it to at all, e.g. ammunition to CA
  no_ship_states  text[] not null default '{}',
  note            text,
  is_live         boolean not null default false,
  qb_item_id      text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now()
);
create index products_live_idx on public.products (is_live) where is_live;
create index products_category_idx on public.products (category);

-- ---------------------------------------------------------------- dealers
create table public.ffl_dealers (
  id                 uuid primary key default gen_random_uuid(),
  licence            text unique not null,
  business_name      text not null,
  address1           text,
  city               text,
  state              char(2),
  zip                text,
  phone              text,
  transfer_fee_cents integer,
  -- set when the licence was last confirmed current against ATF eZ Check
  verified_at        timestamptz,
  created_at         timestamptz not null default now()
);
create index ffl_dealers_zip_idx on public.ffl_dealers (zip);

-- ---------------------------------------------------------------- orders
create sequence if not exists order_ref_seq start 1059;

create table public.orders (
  id              uuid primary key default gen_random_uuid(),
  reference       text unique not null default 'KP-' || nextval('order_ref_seq'),
  placed_at       timestamptz not null default now(),
  customer_name   text not null,
  customer_email  text not null,
  customer_phone  text,
  destination     destination not null,
  ship_address    jsonb,                 -- used when destination = 'door'
  ffl_dealer_id   uuid references public.ffl_dealers,
  status          order_status not null default 'new',
  subtotal_cents  integer not null default 0,
  carrier         text,
  tracking        text,
  note            text,
  qb_invoice_id   text,
  qb_invoice_no   text,
  created_at      timestamptz not null default now(),
  updated_at      timestamptz not null default now(),
  -- a firearm order must name the dealer it is going to. Enforced here so no
  -- application bug can create one without a destination dealer.
  constraint ffl_orders_need_a_dealer
    check (destination <> 'ffl' or ffl_dealer_id is not null),
  constraint door_orders_need_an_address
    check (destination <> 'door' or ship_address is not null)
);
create index orders_status_idx on public.orders (status);
create index orders_placed_idx on public.orders (placed_at desc);

create table public.order_lines (
  id               uuid primary key default gen_random_uuid(),
  order_id         uuid not null references public.orders on delete cascade,
  product_id       uuid references public.products on delete set null,
  sku              text not null,
  name             text not null,
  qty              integer not null check (qty > 0),
  unit_price_cents integer not null check (unit_price_cents >= 0)
);
create index order_lines_order_idx on public.order_lines (order_id);

-- ---------------------------------------------------------------- quickbooks
-- Single row. OAuth refresh tokens live here and must never leave the server;
-- see 0002_rls.sql — this table gets RLS on and no policies at all, so only the
-- service_role key (server-side) can read it.
create table public.qb_connection (
  id            boolean primary key default true check (id),
  realm_id      text,
  access_token  text,
  refresh_token text,
  expires_at    timestamptz,
  connected_at  timestamptz,
  last_sync_at  timestamptz
);

create table public.qb_sync_log (
  id      bigserial primary key,
  at      timestamptz not null default now(),
  level   text not null default 'info' check (level in ('info','warn','error')),
  message text not null
);
create index qb_sync_log_at_idx on public.qb_sync_log (at desc);

-- ---------------------------------------------------------------- updated_at
create or replace function public.touch_updated_at()
returns trigger language plpgsql as $$
begin new.updated_at = now(); return new; end $$;

create trigger products_touch before update on public.products
  for each row execute function public.touch_updated_at();
create trigger orders_touch before update on public.orders
  for each row execute function public.touch_updated_at();

-- ==========================================================================
-- 0002_rls.sql
-- ==========================================================================

-- Row level security.
-- Default posture: deny. Every table below has RLS on, so anything without a
-- matching policy is invisible — including to a leaked anon key.

-- Membership of public.staff is the definition of "is an employee".
-- security definer so the policy can read the table without recursing into its
-- own RLS; search_path pinned so it cannot be shadowed.
create or replace function public.is_staff()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select exists (select 1 from public.staff where id = auth.uid())
$$;
revoke execute on function public.is_staff() from anon;
grant  execute on function public.is_staff() to authenticated;

alter table public.staff         enable row level security;
alter table public.products      enable row level security;
alter table public.ffl_dealers   enable row level security;
alter table public.orders        enable row level security;
alter table public.order_lines   enable row level security;
alter table public.qb_connection enable row level security;
alter table public.qb_sync_log   enable row level security;

-- ---------------------------------------------------------------- staff
-- An employee may see their own row and nobody else's. Adding employees is done
-- from the Supabase dashboard, or by the service_role key. There is no signup.
create policy staff_read_self on public.staff
  for select to authenticated using (id = auth.uid());

-- ---------------------------------------------------------------- products
-- The storefront reads live products with the anon key. That is the only thing
-- the anon key can see anywhere in this database.
create policy products_public_read on public.products
  for select to anon, authenticated using (is_live);

create policy products_staff_read on public.products
  for select to authenticated using (public.is_staff());
create policy products_staff_write on public.products
  for all to authenticated using (public.is_staff()) with check (public.is_staff());

-- ---------------------------------------------------------------- dealers
-- Dealer records include licence numbers. Staff only.
create policy dealers_staff_all on public.ffl_dealers
  for all to authenticated using (public.is_staff()) with check (public.is_staff());

-- ---------------------------------------------------------------- orders
-- Customer names, addresses, and the dealer they are transferring through.
-- Staff only, with no public read of any kind.
--
-- Note there is deliberately no INSERT policy for anon. Orders are created
-- server-side by a Netlify Function using the service_role key, so a browser
-- cannot forge prices or bypass the destination rules.
create policy orders_staff_all on public.orders
  for all to authenticated using (public.is_staff()) with check (public.is_staff());
create policy order_lines_staff_all on public.order_lines
  for all to authenticated using (public.is_staff()) with check (public.is_staff());

-- ---------------------------------------------------------------- quickbooks
-- qb_connection holds OAuth access and refresh tokens.
-- RLS is ON and there are NO policies, by design: neither the anon key nor a
-- signed-in employee can read it from a browser. Only the service_role key,
-- which bypasses RLS and never leaves the server, can touch this table.

-- The log has no secrets, so staff may read it.
create policy qb_log_staff_read on public.qb_sync_log
  for select to authenticated using (public.is_staff());

-- ==========================================================================
-- 0003_seed.sql
-- ==========================================================================

-- Seed the catalogue to match what the storefront currently ships.
-- Safe to re-run: conflicts on sku are updated, not duplicated.

insert into public.products (sku,name,category,price_cents,stock,built_to_order,delivery,no_ship_states,note,is_live) values
 ('act-short','KLOVR Short Action — Burnt Bronze','Actions',139500,8,false,'door','{}',null,true),
 ('act-magnum','KLOVR Magnum Action — Burnt Bronze','Actions',149500,3,false,'door','{}',null,true),
 ('chs-bronze','KLOVR Chassis — Burnt Bronze','Chassis',115000,5,false,'door','{}',null,true),
 ('chs-skel','KLOVR Chassis — Skeletonized','Chassis',115000,0,true,'door','{}',null,true),
 ('rifle-cm','KLOVR Complete Rifle — 6.5 Creedmoor','Rifles',485000,0,true,'ffl','{}',null,true),
 ('rifle-wm','KLOVR Complete Rifle — .300 Win Magnum','Rifles',529000,0,true,'ffl','{}',null,true),
 ('bbl-65','Pre-fit barrel — 6.5 CM, 22″ fluted','Barrels',52000,11,false,'door','{}',null,true),
 ('bolt-sa','Spare bolt assembly','Barrels',38500,6,false,'door','{}',null,true),
 ('opt-3510','3.5–10×40 hunting scope','Optics',64900,6,false,'door','{}',null,true),
 ('opt-41650','4–16×50 long-range scope','Optics',119900,2,false,'door','{}',null,true),
 ('rings-34','34 mm rings — burnt bronze','Mounts',18900,9,false,'door','{}',null,true),
 ('ammo-65','6.5 Creedmoor — 140 gr match','Ammunition',4150,34,false,'door',
   '{CA,MA,NY,IL,NJ}','Ammunition cannot ship to CA, MA, NY, IL, or NJ.',true),
 ('bipod-carb','Carbon bipod, 7–10″','Gear',37900,7,false,'door','{}',null,true),
 ('bipod-atlas','Atlas BT46-LW17 PSR bipod','Support gear',35495,0,true,'door','{}',null,true),
 ('case-48','Takedown rifle case, 48″','Gear',18900,4,false,'door','{}',null,true),
 ('sup-65','Titanium suppressor — 6.5 mm','Suppressors',94900,1,false,'nfa',
   '{CA,DC,DE,HI,IL,IA,MA,NJ,NY,RI}','Form 4 and $200 stamp. Held in our safe until approval.',true)
on conflict (sku) do update set
  name = excluded.name, category = excluded.category, price_cents = excluded.price_cents,
  stock = excluded.stock, built_to_order = excluded.built_to_order, delivery = excluded.delivery,
  no_ship_states = excluded.no_ship_states, note = excluded.note, is_live = excluded.is_live;

insert into public.qb_connection (id) values (true) on conflict (id) do nothing;

-- ==========================================================================
-- 0004_create_order.sql
-- ==========================================================================

-- Order creation.
--
-- The browser sends SKUs, quantities, and a destination. It does not send
-- prices, and nothing it sends about price is read. Everything is priced and
-- re-validated here, inside one transaction, against the catalogue.
--
-- security definer so it can write despite RLS; execute is revoked from anon
-- and authenticated so it can only be reached by the service_role key from
-- netlify/functions/create-order.js.

create or replace function public.create_order(payload jsonb)
returns jsonb
language plpgsql
security definer
set search_path = public
as $$
declare
  v_dest        destination;
  v_ffl_id      uuid;
  v_dest_state  text;
  v_order_id    uuid;
  v_reference   text;
  v_subtotal    integer := 0;
  v_line        jsonb;
  v_prod        public.products%rowtype;
  v_qty         integer;
  v_count       integer := 0;
  v_ffl         jsonb;
begin
  v_dest := (payload->>'destination')::destination;

  if jsonb_typeof(payload->'lines') <> 'array'
     or jsonb_array_length(payload->'lines') = 0 then
    raise exception 'EMPTY_CART';
  end if;
  if jsonb_array_length(payload->'lines') > 40 then
    raise exception 'CART_TOO_LARGE';
  end if;

  -- ---- destination -------------------------------------------------------
  if v_dest = 'ffl' then
    v_ffl := payload->'ffl';
    if v_ffl is null or v_ffl->>'licence' is null then
      raise exception 'FFL_REQUIRED';
    end if;
    -- Cache the dealer. verified_at stays null until the licence has actually
    -- been confirmed current against ATF eZ Check.
    insert into public.ffl_dealers (licence, business_name, address1, city, state, zip)
    values (v_ffl->>'licence', v_ffl->>'business_name', v_ffl->>'address1',
            v_ffl->>'city', upper(v_ffl->>'state'), v_ffl->>'zip')
    on conflict (licence) do update set business_name = excluded.business_name
    returning id, state into v_ffl_id, v_dest_state;
  else
    v_dest_state := upper(payload->'ship_address'->>'state');
    if v_dest_state is null then
      raise exception 'SHIP_STATE_REQUIRED';
    end if;
  end if;

  -- ---- the order ---------------------------------------------------------
  insert into public.orders
    (customer_name, customer_email, customer_phone, destination, ship_address, ffl_dealer_id, note)
  values
    (payload->>'customer_name', lower(payload->>'customer_email'), payload->>'customer_phone',
     v_dest,
     case when v_dest = 'door' then payload->'ship_address' else null end,
     v_ffl_id,
     payload->>'note')
  returning id, reference into v_order_id, v_reference;

  -- ---- lines, priced from the catalogue ----------------------------------
  for v_line in select * from jsonb_array_elements(payload->'lines')
  loop
    v_qty := greatest(1, coalesce((v_line->>'qty')::integer, 1));
    if v_qty > 99 then raise exception 'QTY_TOO_LARGE:%', v_line->>'sku'; end if;

    select * into v_prod from public.products where sku = v_line->>'sku';
    if not found        then raise exception 'UNKNOWN_SKU:%', v_line->>'sku'; end if;
    if not v_prod.is_live then raise exception 'NOT_FOR_SALE:%', v_prod.name; end if;

    -- An item that may only go to a dealer cannot be on a door order.
    if v_prod.delivery <> 'door' and v_dest <> 'ffl' then
      raise exception 'NEEDS_DEALER:%', v_prod.name;
    end if;

    -- And it cannot go somewhere it is not permitted at all.
    if v_dest_state = any (v_prod.no_ship_states) then
      raise exception 'NOT_PERMITTED:%:%', v_prod.name, v_dest_state;
    end if;

    if not v_prod.built_to_order and v_prod.stock < v_qty then
      raise exception 'OUT_OF_STOCK:%', v_prod.name;
    end if;

    insert into public.order_lines (order_id, product_id, sku, name, qty, unit_price_cents)
    values (v_order_id, v_prod.id, v_prod.sku, v_prod.name, v_qty, v_prod.price_cents);

    v_subtotal := v_subtotal + v_prod.price_cents * v_qty;
    v_count := v_count + v_qty;
  end loop;

  update public.orders set subtotal_cents = v_subtotal where id = v_order_id;

  return jsonb_build_object(
    'reference', v_reference,
    'subtotal_cents', v_subtotal,
    'items', v_count
  );
end $$;

revoke execute on function public.create_order(jsonb) from public, anon, authenticated;

-- ==========================================================================
-- 0005_storefront_fields.sql
-- ==========================================================================

-- Fields the storefront renders that the first cut of the schema did not carry.
--
-- filter_key is the shop's filter slug ('action', 'chassis', …) as opposed to
-- `category`, which is the human label ('Actions'). Keeping both means the
-- filter chips do not depend on how a label is spelled.

alter table public.products add column if not exists summary    text;
alter table public.products add column if not exists filter_key text;
alter table public.products add column if not exists sort_order integer not null default 100;

create index if not exists products_filter_idx on public.products (filter_key);

-- Records the last time the storefront was rebuilt, so staff can see whether an
-- edit is live yet. One row.
create table if not exists public.site_meta (
  id                boolean primary key default true check (id),
  last_published_at timestamptz,
  last_published_by text
);
insert into public.site_meta (id) values (true) on conflict (id) do nothing;

alter table public.site_meta enable row level security;
create policy site_meta_staff_read on public.site_meta
  for select to authenticated using (public.is_staff());
-- writes happen from the rebuild function with the service key only

-- ==========================================================================
-- 0006_catalogue_content.sql
-- ==========================================================================

-- Catalogue content, generated from site/index.html by build tooling.
-- Regenerate rather than editing by hand.

update public.products set
  summary = '700 footprint · integral 20 MOA rail · fluted bolt',
  filter_key = 'action',
  sort_order = 0,
  description = array['Cut from 416R stainless, nitrided, then finished in the burnt bronze that started the company. The recoil lug is machined as part of the receiver rather than sandwiched behind the barrel nut, so there is one less joint to move under recoil.','The rail is integral and cut at 20 MOA, which means there is no base to shoot loose and no screws to check. The bolt body is fluted to shed debris and throws at 70°, clearing a 50 mm objective without changing your cheek weld.'],
  specs = '[["Footprint","Remington 700, short action"],["Bolt face",".473 standard"],["Rail","Integral, 20 MOA"],["Bolt","Fluted body, 70° throw, M16 extractor"],["Material","416R stainless, nitrided"],["Finish","Burnt bronze Cerakote"],["Barrel tenon","1.0625 × 16"],["Weight","31.4 oz"],["In the box","Action, bolt, recoil lug"]]'::jsonb,
  images = array['web/p-action-short.jpg','web/hero-action.jpg','web/feat-profile.jpg','web/feat-muzzle.jpg'],
  no_ship_states = '{}',
  note = null
where sku = 'act-short';
update public.products set
  summary = 'Magnum bolt face · 70° throw · M16 extractor',
  filter_key = 'action',
  sort_order = 10,
  description = array['The same receiver, opened up for belted and beltless magnums. Magnum bolt face, longer magazine cut, and the same integral 20 MOA rail.','Built for .300 Win Mag, 7mm Rem Mag, and the PRC family. If you are chambering something long and you want one action to carry it, this is the one.'],
  specs = '[["Footprint","Remington 700, long action"],["Bolt face",".532 magnum"],["Rail","Integral, 20 MOA"],["Bolt","Fluted body, 70° throw, M16 extractor"],["Material","416R stainless, nitrided"],["Finish","Burnt bronze Cerakote"],["Weight","33.8 oz"],["In the box","Action, bolt, recoil lug"]]'::jsonb,
  images = array['web/p-action-magnum.jpg','web/gal-1.jpg','web/hero-action.jpg'],
  no_ship_states = '{}',
  note = null
where sku = 'act-magnum';
update public.products set
  summary = 'Billet 7075 · AICS mags · engraved forend',
  filter_key = 'chassis',
  sort_order = 20,
  description = array['Cut from a single billet of 7075-T6 and hollowed where the material was carrying nothing. What is left is thick where the action sits and where the forend takes a bipod load.','Takes AICS magazines, adjusts for comb height and length of pull, and carries M-LOK along the forend. The roll mark is engraved, not printed.'],
  specs = '[["Material","Billet 7075-T6 aluminium"],["Magazine","AICS pattern, detachable"],["Forend","12″, M-LOK"],["Adjustment","Comb height and length of pull"],["Fits","Remington 700 footprint"],["Finish","Burnt bronze Cerakote"],["Weight","3 lb 2 oz"],["Hardware","Action screws and torque spec included"]]'::jsonb,
  images = array['web/p-chassis-bronze.jpg','web/hero-chassis.jpg','web/gal-5.jpg','web/gal-4.jpg'],
  no_ship_states = '{}',
  note = null
where sku = 'chs-bronze';
update public.products set
  summary = 'Adjustable comb and length of pull',
  filter_key = 'chassis',
  sort_order = 30,
  description = array['The same chassis with the skeleton cuts opened further. Four ounces lighter, and you can see straight through it, which some people love and some people do not.','Built to order in the finish you pick.'],
  specs = '[["Material","Billet 7075-T6 aluminium"],["Magazine","AICS pattern, detachable"],["Forend","12″, M-LOK"],["Adjustment","Comb height and length of pull"],["Fits","Remington 700 footprint"],["Finish","Your choice of house colours"],["Weight","2 lb 14 oz"],["Lead time","4–6 weeks"]]'::jsonb,
  images = array['web/p-chassis-black.jpg','web/gal-2.jpg','web/gal-3.jpg'],
  no_ship_states = '{}',
  note = null
where sku = 'chs-skel';
update public.products set
  summary = '22″ fluted · bronze chassis · sub‑MOA proofed',
  filter_key = 'rifle',
  sort_order = 40,
  description = array['A complete rifle on our own action and chassis, chambered, trued, and bedded on the bench. It leaves with a three-shot group at 100 yards and that target in the case.','Six-five Creedmoor because it does most of what most people need: flat enough for open country, mild enough to shoot well, and cheap enough to practise with.'],
  specs = '[["Chambering","6.5 Creedmoor"],["Barrel","22″ fluted, 1:8, 416R stainless"],["Action","KLOVR short action, integral 20 MOA rail"],["Chassis","KLOVR billet, burnt bronze"],["Muzzle","Threaded 5/8 × 24, capped"],["Trigger","Adjustable, set at 2 lb 8 oz"],["Weight","8 lb 4 oz bare"],["Accuracy","Sub-MOA three-shot guarantee"],["Lead time","10–14 weeks"]]'::jsonb,
  images = array['web/p-rifle-cm.jpg','web/hero-rifle.jpg','web/cfg-stage.jpg','web/gal-1.jpg'],
  no_ship_states = '{}',
  note = null
where sku = 'rifle-cm';
update public.products set
  summary = '24″ fluted · magnum action · sub‑MOA proofed',
  filter_key = 'rifle',
  sort_order = 50,
  description = array['The magnum build, for elk country and the long shots that come with it. Twenty-four inches to get the most out of the case, on the magnum action.','Proofed to the same standard as every complete rifle: three shots, 100 yards, under an inch, target in the case.'],
  specs = '[["Chambering",".300 Winchester Magnum"],["Barrel","24″ fluted, 1:10, 416R stainless"],["Action","KLOVR magnum action, integral 20 MOA rail"],["Chassis","KLOVR billet"],["Muzzle","Threaded 5/8 × 24, radial brake"],["Trigger","Adjustable, set at 2 lb 8 oz"],["Weight","9 lb 1 oz bare"],["Accuracy","Sub-MOA three-shot guarantee"],["Lead time","10–14 weeks"]]'::jsonb,
  images = array['web/p-rifle-mag.jpg','web/gal-1.jpg','web/hero-rifle.jpg'],
  no_ship_states = '{}',
  note = null
where sku = 'rifle-wm';
update public.products set
  summary = '416R stainless · 1:8 · threaded 5/8×24',
  filter_key = 'barrel',
  sort_order = 60,
  description = array['Chambered and headspaced to drop onto a KLOVR action or any 700 footprint with a barrel nut. No gunsmith, no lathe — a wrench and a go gauge.','Fluted to shed weight and heat without giving up much stiffness.'],
  specs = '[["Chambering","6.5 Creedmoor"],["Length","22″"],["Twist","1:8"],["Contour","Fluted sporter"],["Material","416R stainless"],["Muzzle","Threaded 5/8 × 24 with cap"],["Fitment","KLOVR and 700-footprint actions"],["Finish","Nitride"]]'::jsonb,
  images = array['web/p-barrel.jpg','web/cfg-stage.jpg'],
  no_ship_states = '{}',
  note = null
where sku = 'bbl-65';
update public.products set
  summary = 'Fluted body · M16 extractor · short action',
  filter_key = 'barrel',
  sort_order = 70,
  description = array['A second bolt, headspaced to your action if you send us the serial number. Useful if you run more than one barrel.'],
  specs = '[["Action length","Short"],["Bolt face",".473 standard"],["Body","Fluted"],["Extractor","M16-style"],["Throw","70°"],["Finish","Nitride"],["Note","Send your action serial for headspacing"]]'::jsonb,
  images = array['web/p-bolt.jpg','web/hero-action.jpg'],
  no_ship_states = '{}',
  note = null
where sku = 'bolt-sa';
update public.products set
  summary = '30 mm tube · capped turrets · second focal',
  filter_key = 'optic',
  sort_order = 80,
  description = array['A general-purpose hunting scope. Capped turrets so nothing moves in a scabbard, and enough magnification for anything inside four hundred yards.'],
  specs = '[["Magnification","3.5–10×"],["Objective","40 mm"],["Tube","30 mm"],["Focal plane","Second"],["Turrets","Capped, 1/4 MOA"],["Length","12.6″"],["Weight","19.2 oz"]]'::jsonb,
  images = '{}',
  no_ship_states = '{}',
  note = null
where sku = 'opt-3510';
update public.products set
  summary = 'Exposed elevation · 0.1 mil clicks',
  filter_key = 'optic',
  sort_order = 90,
  description = array['Exposed elevation with a zero stop, for people who dial rather than hold over. Fifty millimetre objective for the first and last half hour of light.'],
  specs = '[["Magnification","4–16×"],["Objective","50 mm"],["Tube","34 mm"],["Focal plane","First"],["Turrets","Exposed elevation, 0.1 mil, zero stop"],["Length","13.9″"],["Weight","29.6 oz"]]'::jsonb,
  images = '{}',
  no_ship_states = '{}',
  note = null
where sku = 'opt-41650';
update public.products set
  summary = 'Matched pair · 1.1″ height · 4‑screw caps',
  filter_key = 'mount',
  sort_order = 100,
  description = array['Matched pair, lapped, finished to match our actions. Four screws per cap so the clamping load spreads evenly across the tube.'],
  specs = '[["Tube","34 mm"],["Height","1.1″ centre over rail"],["Caps","Four screws each"],["Material","7075-T6 aluminium"],["Finish","Burnt bronze Cerakote"],["Torque","18 in-lb caps, 65 in-lb clamps"]]'::jsonb,
  images = '{}',
  no_ship_states = '{}',
  note = null
where sku = 'rings-34';
update public.products set
  summary = '20 rounds · boat tail · brass case',
  filter_key = 'ammo',
  sort_order = 110,
  description = array['Match ammunition for load development and practice. Twenty rounds, brass case, boat tail.'],
  specs = '[["Chambering","6.5 Creedmoor"],["Bullet","140 gr boat tail"],["Case","Brass, reloadable"],["Count","20 rounds"],["Restrictions","Cannot ship to CA, MA, NY, IL, NJ"]]'::jsonb,
  images = '{}',
  no_ship_states = array['CA','MA','NY','IL','NJ'],
  note = 'Ammunition cannot ship to CA, MA, NY, IL, or NJ.'
where sku = 'ammo-65';
update public.products set
  summary = 'Picatinny mount · cant and pan',
  filter_key = 'gear',
  sort_order = 120,
  description = array['Carbon legs, aluminium head, cant and pan with a single tension knob. Mounts straight to a rail.'],
  specs = '[["Height","7–10″"],["Mount","Picatinny"],["Movement","Cant and pan, lockable"],["Weight","11.4 oz"],["Legs","Carbon fibre, notched"]]'::jsonb,
  images = '{}',
  no_ship_states = '{}',
  note = null
where sku = 'bipod-carb';
update public.products set
  summary = 'Foam‑lined · lockable · airline rated',
  filter_key = 'gear',
  sort_order = 130,
  description = array['Rated for airline checked baggage, which means lockable with a non-TSA lock as the law requires for firearms.'],
  specs = '[["Internal length","48″"],["Lining","Pluck foam"],["Locks","Two, non-TSA"],["Rating","Airline checked baggage"],["Weight","11 lb"],["Wheels","Yes"]]'::jsonb,
  images = '{}',
  no_ship_states = '{}',
  note = null
where sku = 'case-48';
update public.products set
  summary = '11.4 oz · direct thread 5/8×24',
  filter_key = 'nfa',
  sort_order = 140,
  description = array['Titanium, direct thread, rated to magnum pressures in 6.5. Eleven and a half ounces on the end of a hunting rifle is about as light as this gets.','This is an NFA item. It requires ATF Form 4, fingerprints, and a $200 transfer stamp, and it stays in our safe until your stamp clears — currently 20 to 45 days on eForms.'],
  specs = '[["Calibre","6.5 mm, magnum rated"],["Mount","Direct thread 5/8 × 24"],["Material","Titanium"],["Weight","11.4 oz"],["Length","7.2″"],["Paperwork","ATF Form 4, $200 stamp"],["Restrictions","Not transferable to CA, DC, DE, HI, IL, IA, MA, NJ, NY, RI"]]'::jsonb,
  images = '{}',
  no_ship_states = array['CA','DC','DE','HI','IL','IA','MA','NJ','NY','RI'],
  note = 'Form 4 and $200 stamp. Held in our safe until approval.'
where sku = 'sup-65';

-- The Atlas PSR bipod, added after the original catalogue content. Copy supplied
-- by the manufacturer; the photograph is their studio shot, padded to 3:2 so the
-- legs are not cropped by the card.
update public.products set
  images = array['web/p-bipod-atlas.jpg']
where sku = 'bipod-atlas';

-- ==========================================================================
-- 0007_ffl_directory.sql
-- ==========================================================================

-- FFL directory.
--
-- Source is the ATF listing of active Federal Firearms Licensees, which ATF
-- publishes monthly and makes available to licence holders through eZ Check.
-- It excludes type 03 collectors and type 06 ammunition manufacturers.
--
-- There is no API for eZ Check — ATF has said so. Verifying that one licence is
-- currently valid is therefore a manual lookup a member of staff performs, and
-- verified_at records when they did it. Nothing here scrapes ATF.

alter table public.ffl_dealers add column if not exists licence_name text;
alter table public.ffl_dealers add column if not exists licence_type char(2);
alter table public.ffl_dealers add column if not exists expires_on   date;
alter table public.ffl_dealers add column if not exists source       text;
alter table public.ffl_dealers add column if not exists imported_at  timestamptz;
alter table public.ffl_dealers add column if not exists verified_by  text;

-- Which licence types may actually receive a firearm transfer.
-- 01 dealer · 02 pawnbroker · 07 manufacturer · 08 importer
-- 09/10/11 destructive devices. Deliberately excludes 03 (collector, curio and
-- relic only) and 06 (ammunition manufacturer) — neither can take a transfer.
alter table public.ffl_dealers
  add column if not exists can_transfer boolean
  generated always as (licence_type in ('01','02','07','08','09','10','11')) stored;

create index if not exists ffl_zip_idx    on public.ffl_dealers (zip);
create index if not exists ffl_zip3_idx   on public.ffl_dealers (left(zip, 3));
create index if not exists ffl_state_idx  on public.ffl_dealers (state);

-- ---------------------------------------------------------------- search
-- Public: the checkout needs this before anyone has signed in. security definer
-- so it can read a staff-only table, returning only the columns a customer
-- needs — never the whole row.
--
-- Proximity without geocoding: an exact ZIP beats a shared 4-digit prefix,
-- which beats a shared 3-digit prefix (the same sectional centre), which beats
-- merely being in the same state. Good enough to put the right dealer first.
create or replace function public.find_ffls(p_zip text, p_state text default null, p_limit int default 12)
returns table (
  licence       text,
  business_name text,
  address1      text,
  city          text,
  state         char(2),
  zip           text,
  phone         text,
  expires_on    date,
  proximity     int
)
language sql
stable
security definer
set search_path = public
as $$
  select d.licence, coalesce(d.business_name, d.licence_name) as business_name,
         d.address1, d.city, d.state, d.zip, d.phone, d.expires_on,
         case when d.zip = p_zip                              then 0
              when left(d.zip,4) = left(p_zip,4)              then 1
              when left(d.zip,3) = left(p_zip,3)              then 2
              else 3 end as proximity
  from public.ffl_dealers d
  where d.can_transfer
    and (d.expires_on is null or d.expires_on >= current_date)
    and ( left(d.zip,3) = left(p_zip,3)
          or (p_state is not null and d.state = upper(p_state)) )
  order by proximity, coalesce(d.business_name, d.licence_name)
  limit least(greatest(p_limit,1), 25)
$$;

grant execute on function public.find_ffls(text, text, int) to anon, authenticated;

-- Staff record a manual eZ Check the moment they do one.
create or replace function public.mark_ffl_verified(p_licence text, p_by text)
returns void language sql security definer set search_path = public as $$
  update public.ffl_dealers
     set verified_at = now(), verified_by = p_by
   where licence = p_licence
$$;
revoke execute on function public.mark_ffl_verified(text, text) from public, anon;
grant  execute on function public.mark_ffl_verified(text, text) to authenticated;

-- ==========================================================================
-- 0008_site_events.sql
-- ==========================================================================

-- Site events.
--
-- First-party, on purpose. The privacy page tells customers this site runs no
-- third-party trackers, and firearms customers have a particular reason to care
-- who holds a list with their name on it. Keeping the measurement here means
-- that sentence stays true, and it costs nothing.
--
-- What is deliberately NOT here: no cookie, no durable visitor id, no IP
-- address, no user agent string, no full referrer, no city, and no link of any
-- kind between an event and an order or a customer. The session column is a
-- random value the browser keeps in sessionStorage — it dies with the tab, and
-- its only job is to let a funnel count one person once.

create table if not exists public.site_events (
  id        bigserial primary key,
  at        timestamptz not null default now(),
  -- ephemeral, per browser tab; not a visitor id and never joined to anything
  session   text not null,
  name      text not null,
  props     jsonb not null default '{}'::jsonb,
  path      text,
  -- host only. "duckduckgo.com", never the URL somebody arrived from.
  ref_host  text,
  -- country and state. A shop that cannot ship certain items to certain states
  -- has a real use for this; the city would be precision nobody asked for.
  country   text,
  region    text,
  device    text check (device in ('mobile','desktop'))
);

create index if not exists site_events_at_idx    on public.site_events (at desc);
create index if not exists site_events_name_idx  on public.site_events (name, at desc);
create index if not exists site_events_props_idx on public.site_events using gin (props);

-- Deny by default, like everything else. There is no insert policy at all:
-- writes arrive through netlify/functions/collect.js with the service key,
-- which is the only place event names are validated.
alter table public.site_events enable row level security;

drop policy if exists site_events_staff_read on public.site_events;
create policy site_events_staff_read on public.site_events
  for select to authenticated using (is_staff());

-- ---------------------------------------------------------------- reporting
-- security definer so one is_staff() check gates the lot, search_path pinned so
-- these cannot be shadowed.

-- What happened, and how much of it.
create or replace function public.events_summary(p_days int default 30)
returns table (name text, events bigint, sessions bigint)
language sql stable security definer set search_path = public as $$
  select e.name, count(*), count(distinct e.session)
  from site_events e
  where is_staff() and e.at > now() - make_interval(days => greatest(p_days, 1))
  group by e.name
  order by 2 desc
$$;

-- Searches that found nothing. For a shop this is the most directly actionable
-- thing on the page: it is a list of what people came for and did not get.
create or replace function public.search_gaps(p_days int default 30)
returns table (q text, times bigint, last_at timestamptz)
language sql stable security definer set search_path = public as $$
  select lower(e.props->>'q'), count(*), max(e.at)
  from site_events e
  where is_staff()
    and e.name = 'search'
    and coalesce((e.props->>'n')::int, 0) = 0
    and coalesce(e.props->>'q', '') <> ''
    and e.at > now() - make_interval(days => greatest(p_days, 1))
  group by 1
  order by 2 desc, 3 desc
$$;

-- What people actually spec when they build a rifle. This is stock intelligence
-- that cannot be got any other way — a chambering nobody picks is barrel money
-- sitting on a shelf.
create or replace function public.build_choices(p_days int default 30)
returns table (step text, choice text, picks bigint, sessions bigint)
language sql stable security definer set search_path = public as $$
  select e.props->>'k', e.props->>'v', count(*), count(distinct e.session)
  from site_events e
  where is_staff()
    and e.name = 'build_step'
    and coalesce(e.props->>'k', '') <> ''
    and e.at > now() - make_interval(days => greatest(p_days, 1))
  group by 1, 2
  order by 1, 3 desc
$$;

-- Where checkout loses people. Counted by session so one person hitting Back
-- does not read as two.
create or replace function public.checkout_funnel(p_days int default 30)
returns table (step int, sessions bigint)
language sql stable security definer set search_path = public as $$
  select (e.props->>'step')::int, count(distinct e.session)
  from site_events e
  where is_staff()
    and e.name = 'checkout_step'
    and (e.props->>'step') ~ '^[1-4]$'
    and e.at > now() - make_interval(days => greatest(p_days, 1))
  group by 1
  order by 1
$$;

-- Looked at versus put in a basket, per product.
create or replace function public.product_interest(p_days int default 30)
returns table (sku text, views bigint, carted bigint)
language sql stable security definer set search_path = public as $$
  select coalesce(v.sku, c.sku), coalesce(v.n, 0), coalesce(c.n, 0)
  from (select props->>'sku' as sku, count(*) n from site_events
        where name = 'product_view' and at > now() - make_interval(days => greatest(p_days, 1))
        group by 1) v
  full join
       (select props->>'sku' as sku, count(*) n from site_events
        where name = 'add_to_cart' and at > now() - make_interval(days => greatest(p_days, 1))
        group by 1) c on c.sku = v.sku
  where is_staff()
  order by 2 desc nulls last
$$;

revoke execute on function public.events_summary(int)   from anon;
revoke execute on function public.search_gaps(int)      from anon;
revoke execute on function public.build_choices(int)    from anon;
revoke execute on function public.checkout_funnel(int)  from anon;
revoke execute on function public.product_interest(int) from anon;

-- Nothing here is worth keeping for years. Run this on a schedule (Supabase
-- dashboard → Database → Cron) or call it by hand now and then.
create or replace function public.prune_site_events(p_keep_days int default 400)
returns bigint
language plpgsql security definer set search_path = public as $$
declare n bigint;
begin
  delete from site_events where at < now() - make_interval(days => greatest(p_keep_days, 30));
  get diagnostics n = row_count;
  return n;
end $$;
revoke execute on function public.prune_site_events(int) from anon, authenticated;

-- ==========================================================================
-- 0009_order_notices.sql
-- ==========================================================================

-- Whether anybody was told the order arrived.
--
-- An order sitting in a table nobody opened is the same as no order. Email is
-- sent after the order is committed, so it can fail on its own — and when it
-- does, the row has to say so, or the failure is invisible and the customer is
-- waiting on a reply that was never sent.

alter table public.orders
  add column if not exists notified_at    timestamptz,
  add column if not exists notify_error   text;

comment on column public.orders.notified_at is
  'When the shop and the customer were emailed about this order. Null means nobody has been told.';
comment on column public.orders.notify_error is
  'Why the email did not go out, if it did not. Shown in /admin so it cannot pass unnoticed.';

-- Orders nobody has been told about, oldest first. The one query worth having
-- as a view: if this returns rows, somebody is waiting.
create or replace view public.unnotified_orders
  with (security_invoker = on) as
  select reference, placed_at, customer_name, customer_email, status, notify_error
  from public.orders
  where notified_at is null
  order by placed_at;

-- The function marks its own work. Only service_role reaches this.
create or replace function public.mark_order_notified(p_reference text, p_error text default null)
returns void
language sql
security definer
set search_path = public
as $$
  update public.orders
     set notified_at = case when p_error is null then now() else notified_at end,
         notify_error = p_error,
         updated_at = now()
   where reference = p_reference
$$;
revoke execute on function public.mark_order_notified(text, text) from anon, authenticated;

-- ==========================================================================
-- 0010_product_editor.sql
-- ==========================================================================

-- What the full product editor needs that the schema did not already have.
--
-- Almost nothing, as it turns out: description, specs, images, no_ship_states,
-- summary, filter_key and sort_order were all there from 0001 and 0005. Only
-- two things were missing — a label for how a built-to-order item is described,
-- and somewhere to put a photograph.

-- "Built to order" is right for a rifle we machine and wrong for a bipod we
-- order in from a distributor. Both are the same flag; only the wording differs.
alter table public.products
  add column if not exists made_label text;

comment on column public.products.made_label is
  'How built_to_order reads on the storefront: "Built to order", "Ordered in". Null falls back to the default wording.';

-- ---------------------------------------------------------------- photographs
-- Product photos live in Supabase Storage rather than the repository, because
-- the whole point of this editor is that adding a product does not require a
-- commit. The trade: photos in site/web/ are committed with an AVIF rendition
-- beside them, and these are not — there is no AVIF encoder on a Linux build
-- box. They are served as uploaded. build.js says how many, on every build.
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values ('product-photos', 'product-photos', true, 10485760,
        array['image/jpeg','image/png','image/webp','image/avif'])
on conflict (id) do update
  set public = excluded.public,
      file_size_limit = excluded.file_size_limit,
      allowed_mime_types = excluded.allowed_mime_types;

-- Anyone may look at a product photo — they are on a public shop page. Only
-- staff may put one there or take one away.
drop policy if exists product_photos_public_read on storage.objects;
create policy product_photos_public_read on storage.objects
  for select to anon, authenticated
  using (bucket_id = 'product-photos');

drop policy if exists product_photos_staff_write on storage.objects;
create policy product_photos_staff_write on storage.objects
  for insert to authenticated
  with check (bucket_id = 'product-photos' and public.is_staff());

drop policy if exists product_photos_staff_update on storage.objects;
create policy product_photos_staff_update on storage.objects
  for update to authenticated
  using (bucket_id = 'product-photos' and public.is_staff());

drop policy if exists product_photos_staff_delete on storage.objects;
create policy product_photos_staff_delete on storage.objects
  for delete to authenticated
  using (bucket_id = 'product-photos' and public.is_staff());

-- ---------------------------------------------------------------- guard rails
-- The editor is a form, and a form can be filled in wrongly. These are the
-- mistakes that would reach a customer as a broken page or, worse, as a firearm
-- routed somewhere it may not go.

-- Two-letter state codes, uppercase. 'Ca' or 'Calif' would silently never match
-- the destination and the item would ship somewhere it must not.
alter table public.products drop constraint if exists products_no_ship_states_are_codes;
alter table public.products add constraint products_no_ship_states_are_codes
  check (no_ship_states <@ array[
    'AL','AK','AZ','AR','CA','CO','CT','DE','DC','FL','GA','HI','ID','IL','IN','IA','KS','KY','LA',
    'ME','MD','MA','MI','MN','MS','MO','MT','NE','NV','NH','NJ','NM','NY','NC','ND','OH','OK','OR',
    'PA','RI','SC','SD','TN','TX','UT','VT','VA','WA','WV','WI','WY','PR','VI','GU','AS','MP']::text[]);

-- specs is [["Label","Value"], …]. Anything else and the product page renders
-- empty cells rather than a table.
--
-- The obvious way to write this is a NOT EXISTS over jsonb_array_elements, and
-- it parses — but Postgres refuses a subquery inside a CHECK constraint at
-- execution time. An immutable function holds the same test and is allowed.
create or replace function public.specs_are_pairs(p jsonb)
returns boolean
language sql
immutable
as $$
  select jsonb_typeof(p) = 'array'
     and not exists (
       select 1 from jsonb_array_elements(p) e
       where jsonb_typeof(e) <> 'array'
          or jsonb_array_length(e) <> 2
          or jsonb_typeof(e->0) <> 'string'
          or jsonb_typeof(e->1) <> 'string'
     )
$$;

alter table public.products drop constraint if exists products_specs_are_pairs;
alter table public.products add constraint products_specs_are_pairs
  check (public.specs_are_pairs(specs));

-- A live product with no name, no price or no SKU is a broken card in the shop.
alter table public.products drop constraint if exists products_live_ones_are_complete;
alter table public.products add constraint products_live_ones_are_complete
  check (not is_live or (length(trim(name)) > 0 and length(trim(sku)) > 0));

commit;
