/* Concatenates the migrations into one file you can paste into the Supabase
 * SQL editor in a single go.
 *
 *   node scripts/build-schema.js           write supabase/schema.sql
 *   node scripts/build-schema.js --check   fail if it is out of date
 *
 * The migrations stay the source of truth — this is a convenience for the first
 * run, when there is no CLI and no Docker and ten separate pastes is ten
 * chances to do them out of order. --check runs in CI so the two cannot drift.
 */
const fs = require('fs'), path = require('path');

const ROOT = path.join(__dirname, '..');
const DIR = path.join(ROOT, 'supabase', 'migrations');
const OUT = path.join(ROOT, 'supabase', 'schema.sql');

const files = fs.readdirSync(DIR).filter(f => f.endsWith('.sql')).sort();
if (!files.length) throw new Error('no migrations found');

const rule = '-- ' + '='.repeat(74);
const body = files.map(f => [
  rule,
  `-- ${f}`,
  rule,
  '',
  fs.readFileSync(path.join(DIR, f), 'utf8').trimEnd(),
  ''
].join('\n')).join('\n');

const out = `-- KLOVR Precision — the whole database, in order.
--
-- Generated by scripts/build-schema.js from supabase/migrations/. Do not edit
-- this file; edit the migration and regenerate, or CI will notice.
--
-- Paste the lot into the Supabase SQL editor and run it once, on a new project.
--
-- It is wrapped in a transaction, so if anything fails nothing is applied and
-- you can fix it and paste again. That also means running it a second time on a
-- database that already has these tables stops at the first CREATE TYPE and
-- rolls the whole thing back, rather than half-applying anything. To change
-- something later, write a new migration rather than re-running this.
--
-- ${files.length} migrations, in this order:
${files.map((f, i) => `--   ${String(i + 1).padStart(2)}. ${f}`).join('\n')}

begin;

${body}
commit;
`;

if (process.argv.includes('--check')) {
  const current = fs.existsSync(OUT) ? fs.readFileSync(OUT, 'utf8') : '';
  if (current !== out) {
    console.error('supabase/schema.sql is out of date — run: node scripts/build-schema.js');
    process.exit(1);
  }
  console.log(`supabase/schema.sql is current (${files.length} migrations)`);
} else {
  fs.writeFileSync(OUT, out);
  const kb = (Buffer.byteLength(out) / 1024).toFixed(1);
  console.log(`wrote supabase/schema.sql — ${files.length} migrations, ${kb} KB`);
}
